### ISSUE TITLE
Test : Todo 에서 이슈로 넘기기

### ISSUE THREAD

**Issue by dmsgk** [dmsgk/FiveMinsTracker#2]
- [x] todo에서 이슈로 넘기기
- [x] in progress로 넘기기
- [x]  로컬에서 feature 브랜치를 생성해 코드 작업 후 원격 저장소에 Pull request를 날린다.
- [x] 코드 리뷰를 받고 approve되면 develop 브랜치로 병합한다.
- [x] 해당 feature 브랜치를 삭제한다.
- [x] issue를 닫으면 In progress에서 자동으로 `Done`으로 옮겨진다.
